version: "3"

services:
    grafana:
      image: kamon/grafana_graphite
      container_name: grafana
      ports: 
        - "8080:80"
        - "8081:81"
        - "2003:2003"
        - '8125:8125/udp'
        - "8126:8126"
      volumes:
        - statsd:/src/statsd
        - graphite:/opt/graphite/conf
    
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
    
    kafka1:
      image: wurstmeister/kafka
      depends_on: [zookeeper]
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.99.102
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_BROKER_ID: 0
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LOG_CLEANER_ENABLE: "true"
        KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
        KAFKA_CREATE_TOPICS: "position_updates:40:1:delete,processed_position_updates:40:1:delete"

    kafka2:
      image: wurstmeister/kafka
      depends_on: [zookeeper, kafka1]
      ports:
        - "9093:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.99.102
        KAFKA_ADVERTISED_PORT: 9093
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LOG_CLEANER_ENABLE: "true"
        KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
        # KAFKA_CREATE_TOPICS: "position_updates:40:1:delete,processed_position_updates:40:1:delete"

    kafka3:
      image: wurstmeister/kafka
      depends_on: [zookeeper, kafka1]
      ports:
        - "9094:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.99.102
        KAFKA_ADVERTISED_PORT: 9094
        KAFKA_BROKER_ID: 2
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LOG_CLEANER_ENABLE: "true"
        KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
        # KAFKA_CREATE_TOPICS: "position_updates:40:1:delete,processed_position_updates:40:1:delete"

    position-generator:
      image: reactive-position-generator:1.0
      depends_on: [kafka1, kafka2, kafka3]

    geofence-detector:
      image: reactive-geofence-detector:1.0
      depends_on: [kafka1, kafka2, kafka3]

    websocket-client:
      image: reactive-websocket-client:1.0
      depends_on: [kafka1, kafka2, kafka3]
      ports:
        - "8082:8080"

    battleship-ui:
        image: nginx
        depends_on: [websocket-client]
        ports:
          - "8888:80"
        volumes:
          - /Users/IW-benfoster/Projects/demos/reactive-battleship/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
          - /Users/IW-benfoster/Projects/demos/reactive-battleship/battleship-ui/:/usr/share/nginx/html:ro

    # kafka-statsd:
    #   image: travisjeffery/kafka-statsd 
    #   command: --zookeeper-addrs zookeeper:2181 --statsd-addr grafana:8125 --statsd-prefix kafka

volumes:
  statsd:
  graphite: